### PR TITLE
Add backport for pulsectl

### PR DESCRIPTION
**Pull request by f-fl0**

### CODE REVIEW

**Comment by f-fl0** [comment]
On alpine 3.8 `libpulse` is not available. I try to backport it but it requires `webrtc-audio-processing-dev` which then needs `grpc-dev` which relies on `openssl1.1-compat-dev`, `abseil-cpp-dev` and `samurai`. I think it might be better to deal with this dependency tree in a separate PR if we want to keep supporting alpine 3.8 (melodic EOL is May, 2023 I think).

**Comment by at-wat** [comment]
I think `libpulse` on Alpine 3.8 can be left unprovided if it's not required by any other public packages.

**Comment by f-fl0** [comment]
> I think libpulse on Alpine 3.8 can be left unprovided if it's not required by any other public packages.

I'll leave it as unprovided for now and support `py-pulsectl` only for alpine 3.11 and 3.14. We can revisit this later if needed.

**Review by at-wat — COMMENTED** [review]
As it only support Noetic (Alpine 3.11 and 3.14), py2 support can be dropped.
example: https://github.com/seqsense/aports-ros-experimental/tree/master/backports/py3-xdot

**Review by at-wat — APPROVED** [review]
LGTM

**Pull request merged**
