### PR TITLE
backports/pybind11: add pybind11

### PR DESCRIPTION
**Pull request by Taka-Kazu**
pybind11 package without python files.

ref: https://git.alpinelinux.org/aports/tree/community/py3-pybind11/APKBUILD?h=3.17-stable

### CODE REVIEW

**Comment by at-wat** [comment]
I don't get why this is needed to be diverged from the package in official Alpine repository.
Could you elaborate?

**Comment by Taka-Kazu** [comment]
I'm trying to make APKBUILD for https://github.com/ros2/pybind11_vendor. The package depends on `pybind11-dev`.

The official Alpine repo provides `pybind11` as `py3-pybind11`. `pybind11` package in this PR and `py3-pybind11` contain almost the same files but `py3-pybind11` contains some python files additionally. I confirmed that I can build `pybind11_vendor` with either `py3-pybind11` or `pybind11(-dev)`.

If it's okay to add `py3-pybind11-dev` to `alpine` of `pybind11-dev` (https://github.com/alpine-ros/rosdistro/blob/7b08af054358c3d62c69d2d9b396a3a62d024c90/rosdep/base.yaml#L7504), the changes in this PR is not necessary. But currently, no `python-*` package is specified in  `rosdep/base.yml`. What do you think?

**Comment by at-wat** [comment]
> But currently, no `python-*` package is specified in `rosdep/base.yml` in `rosdistro`.

openembedded also specify `python3-pybind11` for `pybind11-dev`.
I think using official package is much better for future maintenance and also for avoiding package collision (if `py3-pybind11` is installed from official repo due to any other dependencies, installing `pybind11` will fail).

**Comment by Taka-Kazu** [comment]
Thank you for your opinion. I agree with you. I'll close this PR and fix https://github.com/alpine-ros/rosdistro/pull/133

**Pull request closed without merging**
